### ISSUE TITLE
F2

### ISSUE THREAD

**Issue by victor00** [StubbsPvP/RustAdmin#7]
I don't know why, but the F2 isn't working, how can i fix that?

**Comment by StubbsPvP** [comment]
In general autohotkey UI stuff won't show up over a full screen game window. You will need to run Rust in windowed mode or borderless window mode.

If it isn't that it may be a more general problem with your Autohotkey install. 

Sorry I couldn't be more helpful but, I personally haven't played Rust or used this script in years. You might want to seek out somebody that has forked the code more recently for help.

**Comment by victor00** [comment]
It's all good, thank you for the answer. Cheers!
